### ISSUE TITLE
Getting Access Token

### ISSUE THREAD

**Issue by namakujuo** [pinecat/azure-ad-graph-expo#10]
So after setting up the example code and getting a response, access tokens aren't part of the response. How do I get the access tokens? Thanks in advance.

**Comment by pinecat** [comment]
Hi,

This library does not actually return the token.  It only uses it to login the user.  If you really want to use this library to return the token, you can change one line, and it should return the token instead of the response from the MS Graph API.

Line `107`, change from:
```js
return await callMsGraph(tokenResponse.access_token);
```
to:
```js
return tokenResponse.access_token;
```
