### ISSUE TITLE
"Not found" message when calling openAuthSession

### ISSUE THREAD

**Issue by yeguacelestial** [pinecat/azure-ad-graph-expo#14]
I came back to my project after a couple of months, and the openAuthSession was redirecting to a blank page with "Not Found" error.

I tried changing the tokens, but haven't had luck so far.

Am I the only one facing this issue? Did Microsoft change anything on the endpoints?

**Comment by pinecat** [comment]
Hi @yeguacelestial ,

Sorry to hear you are having some issues.  Unfortunately, I do not have access to the Azure Cloud any longer, so it's quite difficult for me to continue testing.  Roughly a year ago, this library was updated to use the the new v2 endpoints.  As far as I'm aware, this hasn't changed on Microsoft's end.  I double checked some of the endpoints we're using from this article: https://docs.microsoft.com/en-us/graph/auth-v2-user.

There are some javascript package vulnerabilities that dependabot picked up.  I can try merging the dependency updates and see if that helps your problem.

**Comment by pinecat** [comment]
Could you also let me know what version (npm/yarn package version) you are using for you app?  Could it be you are trying to use an older version of the library that still uses the old endpoints?  Thanks!

**Comment by pinecat** [comment]
Closing since there has been no response in a few months.

**Comment by yeguacelestial** [comment]
@pinecat sorry dude, I just realised I didn't answer this issue anymore.

Fortunately I managed to fix the problem but I had to really dig into the auth flow in order to understand what was failing and what I was doing.

What I did was to manually generate the PKCE challenge code and interchange it with Azure with expo auth session.

Thank you very much!

**Comment by pinecat** [comment]
@yeguacelestial No worries, just saw this sitting here from a few months back and wanted to do some house cleaning.  Glad you found a workaround for your issue.  Would you suggest this library needs an update to the auth flow?  To my knowledge, the most current auth flow for Azure is documented here: https://docs.microsoft.com/en-us/graph/auth-v2-user, and this is what is leveraged by the lib.  Thanks!

**Comment by yeguacelestial** [comment]
@pinecat I think I would update some things.

I made a custom hook for a project of mine, and I think it simplifies a lot of things you use on yours using the Expo auth session.

I tested it with a Django backend, and its working like a charm.

You can check it here (it follows the PKCE auth flow and redirects the user directly to the Azure Tenant Auth webpage):
https://github.com/yeguacelestial/uanlove/blob/develop/pride/screens/Onboarding/hooks/useAzureAuth.js

**Comment by kieunam123** [comment]
Thank you so much @yeguacelestial, your code really saved my life 


> @pinecat I think I would update some things.
> 
> I made a custom hook for a project of mine, and I think it simplifies a lot of things you use on yours using the Expo auth session.
> 
> I tested it with a Django backend, and its working like a charm.
> 
> You can check it here (it follows the PKCE auth flow and redirects the user directly to the Azure Tenant Auth webpage): https://github.com/yeguacelestial/uanlove/blob/develop/pride/screens/Onboarding/hooks/useAzureAuth.js
