### ISSUE TITLE
how to use it ? 

### ISSUE THREAD

**Issue by roei133** [pinecat/azure-ad-graph-expo#2]
i will be happy if u will help me to config it in my app coz i dont understand how to do it

**Comment by pinecat** [comment]
Could you elaborate on what you mean by "config"?  The [README](https://github.com/pinecat/azure-ad-graph-expo/blob/master/readme.md) has an example of how to use the library function call _openAuthSession()_ and what properties need to be passed into it to work.

**Comment by roei133** [comment]
The read me file and the example little confused me coz im new with the
sso-(single sign on) .
Do you have facebook messanger or something that i could contact with u
directly coz i must ur help it important.

בתאריך יום ה׳, 14 במאי 2020, 19:19, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
In order to use this, you'll need to register an app in Azure AD.  That's where you get the client ID, tenant ID, and client secret from.  Normally you can do this by logging into https://portal.azure.com, with your business' or school's Microsoft account.  You can find more info on how to register an app in Azure AD from Microsoft's docs: [Register App Azure AD](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app).  If your account is with a business or school, you may need someone from your organization to register the app for you.  I do not know whether or not you have access.

I don't really do Facebook.  If you need to contact me directly, the easiest way would be IRC.  You can private message me on [Freenode](https://freenode.net/).  My nick is `pinecat`.

**Comment by roei133** [comment]
I look after "SSO" and i hope your lib is what im looking for .
I need open my app apk with no user op password of azure..it must enter
automatic when i open my app. This is what i need.
Send me link to your irc..i will contact u there

בתאריך יום ו׳, 15 במאי 2020, 04:15, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
This library does not offer no-password sign-in, alone.  In order to have no-password sign-in, you'd need to setup the Microsoft Authenticator App to allow passwordless sign-in of your app which leverages this library.  https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-authentication-passwordless-phone

I can't exactly send a link to IRC.  You can connect to the Freenode IRC network from an IRC client or from their website, https://freenode.net.

**Comment by roei133** [comment]
; i use with the "react-native-azure-ad-2" lib --> link
https://github.com/shedaltd/react-native-azure-ad-2
with this lib i use to enter to my app..but it with no sso ...and i must do
sso . so what are my steps that i need to do  ?
i need to delete this lib from my project or what ?
let me know what should i do from the beginning .



בתאריך יום ו׳, 15 במאי 2020, 04:44, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
If you're using the library that you linked me, there is no need to use this one as well.  They essentially accomplish the same goal.  You only need to pick one, you shouldn't need both.  Also, it looks like that library is using the v2 endpoints.  This library is still on the v1.

**Comment by roei133** [comment]
So u can let me know what i need to do now ? What i should i do to achive
the sso in the enter of my app ?

בתאריך יום ו׳, 15 במאי 2020, 17:27, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
### This Library
If you decide to use this library, you'll have to register an app in the Azure Portal, as outlined by Microsoft here: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app.  Once you do that, you'll need to make an object in your code somewhere with the following properties:
```js
const properties = {
  clientId: '<client_id>',
  tenantId: '<tenant_id>',
  scope: 'user.read',
  redirectUrl: AuthSession.getRedirectUrl(),
  clientSecret: '<client_secret>',
};
```
The `<client_id>`, `<tenant_id>`, and `<client_secret>` are values you get from the Azure Portal when you create your app.  Once you have constructed the object, you can pass it into the _openAuthSession()_ function like so:
```js
let result = await openAuthSession(properties);
```

### The Other Library
If you decide to use the other library you linked me (https://github.com/shedaltd/react-native-azure-ad-2), you will have to go through a similar process of registering an app in the Azure Portal.  But beyond that I am not 100% sure how their library works compared to mine, so you would have to ask that project owner if you don't understand how to use their library.

### Upload Code?
If you want to upload some relevant code from your project into a pastebin (https://pastebin.com/) and link it in this thread, I can try to see what's missing if you're still having trouble.

**Comment by roei133** [comment]
Do u have team viewer ?

בתאריך יום ו׳, 15 במאי 2020, 21:27, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
I don't have teamviewer.  You can use pastebin as a guest, though, so you don't even need an account.

**Comment by roei133** [comment]
U can show me snack.io of ur code lib that do the sso as i want..
Send me link to ur snack an i will check if it works with my details of
azure intune.

בתאריך יום ו׳, 15 במאי 2020, 21:36, מאת rory ‏<notifications@github.com>:

**Comment by roei133** [comment]
Snack.expo.io

בתאריך יום ו׳, 15 במאי 2020, 23:59, מאת Roei It ‏<roei133@gmail.com>:

**Comment by pinecat** [comment]
Here is a snack.  It's using expo version 35, and it's pretty much just a copy paste of the example code: https://snack.expo.io/@pinecat/funny-tortilla.

One thing you have to keep in mind is the redirect.  By default, Microsoft will not allow the redirect URL, so you will have to register the redirect URL in Azure.  So, in the Azure Portal, under the settings for you app, you need to add the redirect URL for your app.  For expo, the redirect URL would be `https://auth.expo.io/<username>/<app-name>`.

The snack will have it's own redirect URL.

**Comment by roei133** [comment]
Whats about the "AuthApp" of expo? Its can do sso as i want ?
Link:
https://docs.expo.io/versions/latest/sdk/app-auth/

בתאריך שבת, 16 במאי 2020, 00:58, מאת rory ‏<notifications@github.com>:

**Comment by roei133** [comment]
Also i need it will go directly without press button as you do..can you
show me new snack with that change?

בתאריך שבת, 16 במאי 2020, 00:58, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
My library does not use Expo's AppAuth.  Here is a snack which launches the login automatically: https://snack.expo.io/@pinecat/intelligent-truffle.

**Comment by pinecat** [comment]
I made an edit to the above snack, so that it wouldn't keep launching multiple auth sessions.  There is one line commented in the render function.  If you uncomment that, it will launch the login automatically.

**Comment by roei133** [comment]
So what is the diffrent between ur lib and the AuthApp ? Its do the sso
both no ?

בתאריך שבת, 16 במאי 2020, 02:39, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
My library also queries the Microsoft Graph API, to return user data from Azure AD.  AuthApp does not inherently do this.

**Comment by roei133** [comment]
So its the sso that i need ?

בתאריך שבת, 16 במאי 2020, 16:55, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
If you just want to log a user in, then yes you just need SSO.

**Comment by roei133** [comment]
So if i will send u my app.js so can you try replace the login of my old
lib "react-native-azure-ad-2" with your sso login ?

בתאריך שבת, 16 במאי 2020, 17:31, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
I can't just write the code for you.  The code you write will be highly dependent on your use-case, and if you run into issues down the line and have parts of your code that you don't fully understand, that would be very bad.  Also, replacing that library with this one won't be just a simple swap.

**Comment by roei133** [comment]
where i should put my redirecturi ? i dont understand
this is the object i made :

const azureAdAppProps = {
clientId: 'here i put my client id',
tenantId: 'here i put my tenantid',
scope: 'user.read',
redirectUrl: AuthSession.getRedirectUrl(),
clientSecret: 'i no have client secret so i leave empty',
};

so what is missing ? coz now it give me error message :
" AADSTS50011: The reply url specified in the request does not match the
reply urls configured for the application "

can u let me know what to do please ?

**Comment by roei133** [comment]
the clientSecret is a must ? if i leave it empty ' '  , so its ok or i must put it inside the object ? 
also " redirectUrl: AuthSession.getRedirectUrl() " , i shuold leave it as is ? i dont need to change it or write something inside right ?

**Comment by pinecat** [comment]
You must create a client secret in the 'Certificates & Secrets' tab of your app in the Azure Portal.  https://www.inkoop.io/blog/how-to-get-azure-api-credentials/

In a production application, _AuthSession.getRedirectUrl()_ will redirect to the URL: "https://auth.expo.io/@username/app-name".  You can of course use a different redirect URL, but this function is the easiest way to get the URL for a production environment.
You must register this URL (or the redirect URL you choose) in the Azure Portal under the 'Authentication' tab of your app.  For testing, (i.e. not running the app in a production environment) you will have to figure out the redirect URL yourself, as it is unique to your dev environment.
https://stackoverflow.com/questions/49268418/when-registering-an-app-on-azure-active-direct-what-redirect-uri-or-sign-on

**Comment by roei133** [comment]
I ask again about the redirect url , after i get it from the portal where i
put it in the code ? Or should i leave the *AuthSession.getRedirectUrl() as
is it and not change it.. can u sand me example of the object how its
should be ? Coz i got confused..*
*I put the client id ,tenant id,scope and i will put the secret hope
tomorrow..but the **AuthSession.getRedirectUrl() ileave this function with
no change or add inside it something ?*

בתאריך יום א׳, 17 במאי 2020, 20:41, מאת rory ‏<notifications@github.com>:

**Comment by pinecat** [comment]
If you want to be redirected back to your app after you login, you should use AuthSession.getRedirectUrl().  If you want to be redirected to a different webpage, you should use the address of that instead.
