### ISSUE TITLE
example code doesnt work

### ISSUE THREAD

**Issue by roei133** [pinecat/azure-ad-graph-expo#4]
https://snack.expo.io/@roei133/intelligent-truffle
this is my snack with your example and it doesnt work for me.
hope you can let me know why it doesnt work .

**Comment by AlmondBro** [comment]
Hi Roei133,

I notice there are several typos in your snack,  such as missing a constructor; be sure to correct them. 

The README for this repository has been updated as well as several dependent modules. Be sure to have the latest Expo (v37) installed and used. 

Try this sample code I modified from your snack, and run it on your actual expo app:

```
import React, { Component } from 'react';
import { StyleSheet, View, Text, Button } from 'react-native'
import * as  AuthSession from 'expo-auth-session';
import { openAuthSession } from 'azure-ad-graph-expo';


const azureAdAppProps = {
  clientId: 'ea00ca9e-8c37-4520-8d80-2c2bb9239bf8',
  tenantId: 'aad037b1-bb94-4ebf-9e82-a797fc3841f2',
  scope: 'user.read',
  redirectUrl: AuthSession.makeRedirectUri(),
  clientSecret: 'P5bV-h93JPDu.i7OYqi.s4rSqg~w8l1P_~',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            result :  null
        }; //end this.state
    } //end constructor


  render = async () => {
    let result = await openAuthSession(azureAdAppProps);
    this.setState({ result: result }); 
    return (
            <View style={styles.container}>
              {this.state.result ? (
                <Text>{JSON.stringify(this.state.result)}</Text>
              ) : <Text>Nothing to see here.</Text>}
            </View>
        );
  } //end render() 
} //end App class

export default App;
```

**Comment by roei133** [comment]
i get an error when i run your code.
try to run it on the expo snack and you will see .
this is the snack : 
https://snack.expo.io/@roei133/295ac8

![image](https://user-images.githubusercontent.com/6755278/82778985-a5da9680-9e5b-11ea-9ba6-650738d079ee.png)

**Comment by AlmondBro** [comment]
Hi @roei133,

I am getting that error as well; strange was not there before. I will get back to you a working snack.

**Comment by roei133** [comment]
@JuanDavidLopez95  i didnt see your change yet in the code.
i will be happy to see working snack with the **"SSO" (Single Sign On)** which mean that the app should be open directly with no asking the user for password or user, it should be directly coz you have the object with all the parameters .

**Comment by AlmondBro** [comment]
Hi @roei133,

I am still attempting to dissipate that error. I will notify you as soon as I do.

**Comment by roei133** [comment]
Its so so important to me . I hope you will fix it soon .

בתאריך יום ד׳, 27 במאי 2020, 17:41, מאת Juan David Lopez Londoño ‏<
notifications@github.com>:

**Comment by AlmondBro** [comment]
Hi @roei133 ,

I was finally able to get a working Snack; hopefully it functions on your end -- the current expo snack previewer is **very** **buggy**.

You can view such a snack [here](https://snack.expo.io/@almondbro/azure-ad-graph-expo-example-for-roei133). 

Be sure to replace `AuthSession.getRedirectUrl()` with `AuthSession.makeRedirectUri()` in your actual Expo project. This was a workaround, along with lowering the Snack Expo SDK one version down to v36, to get this to function in the Snack player. 

Here is a screenshot as proof of it working on my end:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/10659877/83092755-d0db0b00-a052-11ea-88d9-c189dd24e414.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/10659877/83092763-dafd0980-a052-11ea-8222-92df1d9b9149.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/10659877/83092791-e8b28f00-a052-11ea-89ca-18193f9da483.png">

**Comment by roei133** [comment]
But i need it to go inside my app without asking for password and
username..
It must be SSO , once you open the app so you go directly inside app.
Can you help me with that ?

בתאריך יום ה׳, 28 במאי 2020, 05:47, מאת Juan David Londoño ‏<
notifications@github.com>:

**Comment by AlmondBro** [comment]
@roei133,

For your app to directly take you to your Single Sign On (S.S.O.) page, you must supply a `domainHint` value to the `azureAdAppProps` object, like the example in the _README_ : 


```
const azureAdAppProps = {
        clientId        :   AZURE_CLIENT_ID,
        tenantId        :   AZURE_TENANT_ID,
        scope           :   'user.read',
        redirectUrl     :   AuthSession.makeRedirectUri(),
        clientSecret    :   AZURE_CLIENT_SECRET,
        domainHint      :   AZURE_DOMAIN_HINT,
        prompt          :   'login'
};
```

**Comment by roei133** [comment]
I did this object as well in my first example, you can see.
U can show me sso with my object ?

בתאריך יום ה׳, 28 במאי 2020, 06:21, מאת Juan David Londoño ‏<
notifications@github.com>:

**Comment by AlmondBro** [comment]
@roei133 

You need to supply the parameter (with a value) of `domainHint` in your Azure AD config object. What is the URL of your S.S.O. page?

**Comment by roei133** [comment]
@JuanDavidLopez95  I have 3 issues : 
1. **What is the URL of your S.S.O. page?**  - Do you mean what is my redirect url ?
2. After press the button and put my detailes I got an error  AADSTS650053 asked for scopeuser.readnull
3. domainHint - How can i get it ? can you show me where is it ?

**Comment by AlmondBro** [comment]
@roei133 

Yes, what is the web site which hosts the single sign on for users of your organization? The domainHint is the same or closely tied to your single sign on url. (this is not the same as the expo `makeRedirectUri()` )

An example of a site which hosts an Azure AD SSO page is https://sts.contoso.microsoft.com (this is just an example, not an actual live site).

**Comment by pinecat** [comment]
@roei133 Are you still having issues with the domain hint?

**Comment by lc3t35** [comment]
For information, I was able to connect for standard Office365 user account with these config

```
  scope: configAuthOutlook.scopes,
  clientId: configAuthOutlook.clientId,
  tenantId: 'common',
  redirectUrl: AuthSession.makeRedirectUri(),
  prompt: 'login',
  domainHint: 'login.microsoftonline.com'
```

**Comment by jodybrewster** [comment]
I was looking in the source, is it possible there's a typo? It looks like the example has 'redirectUrl' and the code is looking for 'returnUrl'.

**Comment by yeguacelestial** [comment]
aye @pinecat , great work my friend.

I'm just having issues grasping all this auth flow.

On my Azure AD, what should I put on redirect uri? When I sign in with my account, I keep getting "No reply addresses for the application". 

I'm trying to integrate this with my Django backend.

**Comment by AlmondBro** [comment]
Hi @yeguacelestial,
 I cannot recall what the exact format is for the redirect URL to be specified in Azure AD. However, add these 4 in your Azure AD app manifest. I have all these (with my specific expo username and project) in one of my Expo apps which utilize this module:

```
{
	"url": "exp://expo.io/@username/name-of-expo-project",
	"type": "InstalledClient"
},
{
	"url": "https://expo.io/@username/name-of-expo-project",
	"type": "InstalledClient"
},
{
	"url": "https://auth.expo.io/@username/name-of-expo-project",
	"type": "Web"
},
{
	"url": "appschemel://redirect",
	"type": "InstalledClient"
},
```

Let us know whether or not this provides you with the solution.

**Comment by pinecat** [comment]
@yeguacelestial,

You'll want to use `AuthSession.makeRedirectUri()`.  You can import AuthSession to your Expo project like so:
```
import ...
import * as AuthSession from 'expo-auth-session';
```

Also, adding the URLs to your Azure AD app manifest is a good idea as well, so thank you @JuanDavidLopez95.  If you are still having trouble getting this to work, please let me know what version of Expo you're using.  Thanks!

**Comment by kieunam123** [comment]
> configAuthOutlook



> For information, I was able to connect for standard Office365 user account with these config
> 
> ```
>   scope: configAuthOutlook.scopes,
>   clientId: configAuthOutlook.clientId,
>   tenantId: 'common',
>   redirectUrl: AuthSession.makeRedirectUri(),
>   prompt: 'login',
>   domainHint: 'login.microsoftonline.com'
> ```

Hi. what is your "configAuthOutlook" code?

**Comment by lc3t35** [comment]
@kieunam123 here you are : 

```
configAuthOutlook = {
   clientId: '.....',
   scope: 'openid offline_access profile user.read calendars.read'
}
```
