### ISSUE TITLE
the code example doesnt work

### ISSUE THREAD

**Issue by roei133** [pinecat/azure-ad-graph-expo#5]
@pinecat please help me with my issue, i try many times your example and also the example of @JuanDavidLopez95 Juan David Lopez Londoño but nothing happen and all the times i got an errors. please show me snack with my object (client_id, secret...) coz all my details in the object are ok and i dont understand whats wrong .
i just want go inside my app with SSO and just all .

**Comment by pinecat** [comment]
@roei133 I apologize for getting back to this so late, I thought it was part of the other thread.  Please continue using that one as of now, I will respond over there.
