### ISSUE TITLE
How to go back to app after successful login?

### ISSUE THREAD

**Issue by namakujuo** [pinecat/azure-ad-graph-expo#9]
Everything works fine, but after successful sign in it does not go back to the app, but remains in the browser. How do you do this?

![image](https://user-images.githubusercontent.com/66373379/96627106-62873580-12de-11eb-8f79-717543d966d0.png)

**Comment by pinecat** [comment]
@namakujuo If everything is setup correctly, it should redirect back to the app automatically.  You may have to set a slug for your project in `app.json` for this to work properly, however.  See: https://docs.expo.io/workflow/configuration/.

If setting the slug does not work, please let me know what version of Expo you are using.  Thanks!

**Comment by namakujuo** [comment]
Hi, thanks for the timely reply. 

Turns out that I didn't add the expo development url to the azure app. So everything works fine now! Thanks for the reply!

**Comment by pinecat** [comment]
Glad you got it working!
